### ISSUE TITLE
Daily client requests exceeded - [Fix]

### ISSUE THREAD

**Issue by AustinPaquette** [mileswd/mac2imgur#103]
I'm just making this here to help anyone who googles the issue, finds this repo and then doesn't want to sift through the other issue looking for context as found in #100 

---

## Full credits to @sn0w [here](https://github.com/mileswd/mac2imgur/issues/100#issuecomment-246596977)

- [x] Get the rate limit error
- [x] Quit Mac2Imgur
- [x] Create new Imgur API credentials at https://api.imgur.com/oauth2/addclient

`Application Name`: <kbd>Anything You'd Like</kbd>
`OAuth 2 authorization WITH a callback URL`
`Callback URL`: mac2imgur://
`Email`: <kbd>Your email</kbd>
`Description`: Creating to use with Mac2Imgur local application

- [x] Then in **terminal** enter:

```
cd /Applications/mac2imgur.app/Contents/MacOS
cp mac2imgur mac2imgur.bak
perl -pi -e 's/5867856c9027819/CLIENT_ID/g' mac2imgur
perl -pi -e 's/7c2a63097cbb0f10f260291aab497be458388a64/CLIENT_SECRET/g' mac2imgur
```

### (replace CLIENT_ID and CLIENT_SECRET with the data from step 3)

After the replacement mac2imgur starts and opens your browser where you have to re-authenticate again.

---

Tested with:
- Perl v5.24.0 on OSX 10.11.6
- Perl v5.18.2 on OSX 10.11.6

**Comment by Daniel131313** [comment]
I am totally new to anything programming and am having the same exceeding the daily limit issue. I had no trouble finding my new Client_ID and Client_secret but how do I find and enter them into the terminal center? I tried copying and pasting everything listed above with my Client ID and Client secret ID replacing the numbers but it wont work still

**Comment by tuck182** [comment]
Don't replace the numbers with your own, replace the "CLIENT_ID" and "CLIENT_SECRET" strings.  So if your client id is `12345`, you'd do:

```
perl -pi -e 's/5867856c9027819/12345/g' mac2imgur
```

**Comment by mileswd** [comment]
See https://github.com/mileswd/mac2imgur/issues/100#issuecomment-248688560
