### ISSUE TITLE
All images are getting uploaded twice

### ISSUE THREAD

**Issue by joren** [mileswd/mac2imgur#111]
I also get two notification, one for each upload.

For example this http://i.imgur.com/xycSPVS.jpg and this http://i.imgur.com/A0p8FB6.jpg image.
When I enable confirmation it also ask me twice to upload it.

**Comment by gitguys** [comment]
Are you uploading with or without account info?  I'm uploading without being signed into imgur and it's working without that issue when I drag-n-drop images to the menubar icon.  I'm using Sierra 10.12.2, BTW.

**Comment by jeremybras** [comment]
Same here, Sierra, logged in on imgur, and it's uploading twice.

**Comment by mileswd** [comment]
This should be resolved in the latest update. Thanks for reporting. 👍
