### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by gitguys** [mileswd/mac2imgur#118]
What's the privacy policy for this app?  Is any user data kept at all?

**Comment by mileswd** [comment]
The only data mac2imgur stores is kept on your local machine (preferences etc) - however the application does use the following services:
- Imgur - [Privacy Policy](http://imgur.com/privacy)
- Fabric (Crashlytics) - [Privacy Policy](https://try.crashlytics.com/terms/privacy-policy.pdf)
- Fabric (Answers) - [Privacy Policy](https://answers.io/img/onepager/privacy.pdf)

Hope this helps 👍
