### ISSUE TITLE
Custom keyboard shortcuts?

### ISSUE THREAD

**Issue by SmeXhy** [mileswd/mac2imgur#119]
Is there any option?

**Comment by mileswd** [comment]
The application uses the built in screenshot functionality of macOS, so you can change the default screenshot keyboard shortcuts from `System Preferences`:

![screen shot 2017-07-08 at 00 02 23](https://user-images.githubusercontent.com/5622554/27980046-92880788-6372-11e7-8d54-ed29c0593561.png)
