### ISSUE TITLE
stuck on uploading

### ISSUE THREAD

**Issue by dwlim** [mileswd/mac2imgur#34]
Occasionally the app will change to the uploading icon and get stuck, forcing me to quit and restart it

**Comment by mileswd** [comment]
@dwlim @bufordtaylor Does this issue still occur with the latest version of mac2imgur and OS X?

**Comment by bufordtaylor** [comment]
Nope, all good.

**Comment by mileswd** [comment]
Closing as the issue appears to have been resolved.
