### ISSUE TITLE
UI does not present deletion link, and would be nice to have a review prompt

### ISSUE THREAD

**Issue by comex** [mileswd/mac2imgur#38]
I've been looking for something to replace Dropbox's crappy auto screenshot uploader.  Found this repository through imgur.com/tools, but it's not quite satisfactory for me as is, so here's two feature requests (for whatever they're worth).

For me at least, it's easy to accidentally include sensitive information in a screenshot, so it's essential for an auto uploader to allow deletion after the fact.  imgur gives you a deletehash in the upload response, but it does not appear in this application's UI...  Perhaps the menu item could include a list of recent uploads, along with a delete option for each.

Also, while this is less important, it would be nice to have an option to prompt before uploading (optimally showing the contents of the screenshot) to help prevent unwanted images from being uploaded in the first place.

**Comment by mileswd** [comment]
Thanks for the feedback - I have implemented both of your requests :)

**Comment by mileswd** [comment]
If possible, it'd be great if you could try running the project before I push out an update, just to ensure that you're satisfied with how I've implemented your requests.
