### ISSUE TITLE
Add ability to drop file to icon in menubar

### ISSUE THREAD

**Issue by joeynotjoe** [mileswd/mac2imgur#40]
I love this simple app, it's incredibly useful! The only feature I find to be missing is the ability to drop an image file onto the menu bar icon, and have it be uploaded.

Once this is complete, I think it's safe to say this will be the ultimate screenshot app!

Thanks!

**Comment by mileswd** [comment]
Sorry for the late response, I plan to add this feature very soon.
It will most likely be pushed out as an automatic update over the next week or so :)

**Comment by joeynotjoe** [comment]
No worries! This is great news. I use your app hundreds of times per day, thanks for the great work!
