### ISSUE TITLE
Ability to upload to custom SFTP

### ISSUE THREAD

**Issue by syabro** [mileswd/mac2imgur#42]
It'll be great. imgur has been banned some domains I need to post :(

**Comment by dch** [comment]
How about adding generic HTTP POST/PUT support? e.g. upload to a mongo or couchdb instance.

**Comment by orditeck** [comment]
That would be awesome. I'm currently using FileShuttle but there is no more development. FileShuttle also allow to upload any file type and it even auto-zip stuffs when you drag multiple files on it! That would be some awesome features to add to mac2imgur, but according to the software name I'm not sure this is planned right?

**Comment by lindskogen** [comment]
Since the whole idea of this app is to upload to imgur I would recommend you to look elsewhere?

**Comment by PunKeel** [comment]
I started developing @Screamshot to handle this, based on mac2imgur's code, and I think the code is still working ... But hadn't time to manage it properly (No build available, for instance)

**Comment by mileswd** [comment]
Unfortunately I think this is out of scope for mac2imgur. The application itself is heavily integrated with Imgur itself and supporting any other upload destination would not only require restructuring, but it detracts from the primary purpose of the application.

Sorry! 😢
