### ISSUE TITLE
Images not automatically uploading

### ISSUE THREAD

**Issue by AndreasBackx** [mileswd/mac2imgur#43]
Images do not seem to upload for some reason now. It worked great in the past for me, but it suddenly stopped working. I'm on build 115, I tried compiling mac2imgur myself on the latest xCode 6.3 beta but I'm getting a ton of errors. Even after fixing the warnings with the recommended fixes by xCode and archiving it to a .app file it just crashes on launch. After removing the app from my Applications folder, restarting my Mac and signing out and in of my Imgur account it still doesn't seem to work. Images remain on my Desktop but are not being touched. Uploading when I select the image itself works fine though.

I'm running OS X Yosemite 10.10.3.

**Comment by PunKeel** [comment]
Duplicate of #41

**Comment by mileswd** [comment]
@AndreasBackx Exactly as @PunKeel said, unfortunately this is an OS X issue.

I'm currently downloading the latest 10.10.3 seed (released recently) and I'll check whether or not the issue is still present.

**Comment by AndreasBackx** [comment]
Can you upload a release if it's fixed in a newer version?

**Comment by mileswd** [comment]
Will do! :smile:

**Comment by mileswd** [comment]
I haven't noticed any problems on the latest beta 10.10.3 (14D105g) - this issue may have been resolved by Apple :+1:

**Comment by PunKeel** [comment]
Would be so great! <3

**Comment by AndreasBackx** [comment]
@mileswd You're right. Seems to work on the dev release. Thank you for the heads up!
