### ISSUE TITLE
Multiple display screenshot support

### ISSUE THREAD

**Issue by AndreasBackx** [mileswd/mac2imgur#44]
Currently when I use the shortcut Shift+Cmd+" it will take a screenshot of every display and quickly upload them one after another. It will then quickly paste the link to the clipboard for every display you have, but it's so quick that you probably can only get one link. It would be cool if the following features could be added:

1. Only upload the display with the active window or where the cursor is located.
2. Upload all of the images in an album and paste the album link to the clipboard.
3. Glue the images together like Windows and some Linux print screen command (forgot the name) do when taking a screenshot. This is handy because people then see how you have your screens organised.

I haven't looked at how you know whether there is a new screenshot. But if it's based on an event that OS X fires or whether you watch the directory of the screenshots, solution 1 and 2 might be the easiest to add. Perhaps even add new shortcuts for every option.

**Comment by mileswd** [comment]
Unfortunately, OS X has no API whatsoever that provides any functionality in regards to taking screenshots. Consequently, the only way of detecting screenshots is through monitoring for when files are saved.

This means we cannot control screen capturing, nor collect any information about screenshots (aside from the file information itself, e.g. the file name, file size).

Sadly, as far as I know, it is currently (practically) impossible for us to implement your ideas. Even though I personally think they would be good features, it is out of my control and entirely up to Apple's engineering decisions.

**Comment by Tyilo** [comment]
> Unfortunately, OS X has no API whatsoever that provides any functionality in regards to taking screenshots.

Can't you just use `/usr/sbin/screencapture`?

**Comment by mileswd** [comment]
>Can't you just use /usr/sbin/screencapture?

@Tyilo If I recall correctly, the screenshot keys in OS X are essentially bound to ```/usr/sbin/screencapture``` (with different arguments) - accessing it directly wouldn't make any difference, I think.

**Comment by Tyilo** [comment]
@mileswd You could make your own keyboard shortcut listener, which either overrides the built-in one or uses a different shortcut. You could then invoke `/usr/sbin/screencapture` and do what you want with the image(s) created, eg. stitch them together.

**Comment by mileswd** [comment]
@Tyilo I'm not sure how it would be possible to identify whether the screenshots are part of a set (such as three screenshots of three separate screens).

**Comment by mileswd** [comment]
The simplest solutions I can think of for this issue are:
>Only upload the display with the active window or where the cursor is located. [don't take a screenshot of every display]

Press CMD + SHIFT + 4, then click and drag diagonally from one corner of the screen to another, therefore capturing only the current screen.

>It will then quickly paste the link to the clipboard for every display you have, but it's so quick that you probably can only get one link.

Click the notifications button on the status bar (top right corner) and ensure you are looking at the "Notifications" tab. You can see the history of recent screenshots here (under "mac2imgur") and clicking a notification will open the relevant image in your browser.

![](http://i.imgur.com/OSgrLcj.png)

**Comment by AndreasBackx** [comment]
Perhaps show a notification message asking whether to make an album from the previous images that were taken with less than 2 seconds or so between them?

**Comment by PunKeel** [comment]
It means waiting two seconds before uploading each screenshot, to see if another one is also taken at the same time.
I'm unsure that it's a good idea, then, two seconds is not that much, but still can't be ignored

**Comment by AndreasBackx** [comment]
@PunKeel Upload the images as usual and afterwards you can probably make those images an album via the Imgur API and then paste that link to your clipboard.

**Comment by mileswd** [comment]
Unfortunately, I think I'm going to have to decline this feature request for now, my reasoning is as follows:
- This request is out of scope when comparing it to the purpose of the application, mac2imgur is not involved in the taking of screenshots, it is simply the middleman that uploads screenshots to imgur: you could use a different screencapture application
- There is no proper/accurate way to do this, an implementation would include the risk of false positive detection or delays for the end user - this would be obtrusive
- There hasn't been much demand for such a feature (I assume that most users don't have multiple displays)
- This request would require a large amount of work
- I don't have more than one monitor, so I would struggle to develop/test this

However, I will certainly reconsider this if Apple do add an API that allows such functionality.
