### ISSUE TITLE
Mac2Imgur stops working after a while?

### ISSUE THREAD

**Issue by Rooflessx** [mileswd/mac2imgur#46]
Mac2Imgur doesn't upload images after an amount of time. I have to quit and open the program for it to work again. Can this be looked at?

**Comment by mileswd** [comment]
Sure, could you possibly give me a little more information?

It'd be handy to know:
- OS X version/build
- Any errors logged by mac2imgur in ```Console.app```
- Any other relevant information

Thanks in advance

**Comment by Rooflessx** [comment]
OS X 10.10.2
Errors - haven't checked but will update if I find any.

**Comment by mileswd** [comment]
Does this issue still occur on 10.10.3?

**Comment by dch** [comment]
I'm getting this on `10.10.3 (14D136)` myself with `mac2imgur 3.0 (build 153) `. nothing of immediate interest in console.log

```
Apr 28 09:13:21 akai.skunkwerks.at mac2imgur[2152]: [Crashlytics] Version 3.0.6 (40)
Apr 28 09:13:29 akai com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
Apr 28 09:13:45 akai.skunkwerks.at iTerm2[262]: Time to encode state for window <PseudoTerminal: 0x7fd862a35420>: 0.0005579590797424316
```

No XCode app installed but the command line tools are present.

**Comment by mileswd** [comment]
@dch I'm not sure what could be causing this, but I'd love to find out.

What is the output when you run ```defaults read com.apple.screencapture```?

**Comment by dch** [comment]
```
2015-04-28 13:49:52.382 defaults[3416:123839] 
Domain com.apple.screencapture does not exist
```

BTW I noticed that cloudapp simply watches the screen dump directory, fwiw.

**Comment by mileswd** [comment]
@dch Sorry for the late reply. Does this issue still occur?

**Comment by dch** [comment]
yup, in fact app doesn't work at all for me any more. nothing logged in console.app, nothing uploaded either.

**Comment by mileswd** [comment]
@dch Thanks for the feedback. I'm going to work on an alternative monitoring method and I'll keep you posted.

**Comment by mileswd** [comment]
@dch Could you please try this development build?
https://www.dropbox.com/s/zd2dqzee6klh4zm/mac2imgur.zip?dl=1

This build has the screenshot detection code stripped to the bare minimum, so for your safety any detected screenshots will cause an alert popup, but won't actually be uploaded.

**Comment by dch** [comment]
@mileswd sorry just checking back in, `v3.0 (174)` works brilliantly, thanks so much!

**Comment by mileswd** [comment]
@dch Awesome - glad to hear it.

--

Closing this issue due to no response from @Rooflessx
