### ISSUE TITLE
Resizing?

### ISSUE THREAD

**Issue by AndyBurkeee** [mileswd/mac2imgur#47]
Whenever I take a screenshot with mac2imgur, it resizes it and makes it much larger. How can i fix this?

**Comment by mileswd** [comment]
Could you possibly provide an example of an image that has been resized?

Could you also tell me what version and build of OS X you are running?

Thanks in advance.

**Comment by AndyBurkeee** [comment]
Running Yosemite and here's a screen cap of this comment. Much bigger than it should look.

https://i.imgur.com/HitKyYQ.png

**Comment by mileswd** [comment]
Here's an extract from an [article](https://cloudup.com/blog/the-retina-screenshot-problem) that explains this problem particularly well:

>High DPI displays, or more popularly known as "Retina" displays thanks to Apple, have become increasingly common over the past couple of years. These displays pack a visual punch with many more pixels per square inch than your typical LCD monitor.

>A Retina MacBook Pro display has roughly a 2:1 pixel density ratio compared to a MacBook Air. To compensate, OS X has to double the pixels it uses to render UI elements and images. The double space allows for more detail in the rendering that the user benefits from overall.

>Regular vs. Retina screenshots:

>Let's quickly take a look at what happens when we use OS X's built-in Screenshot taking tool to capture a "Directory" icon on these two screens.

>![Regular OS X Screenshot](https://cloudup.com/iGTw7ADppZt+)

>It should not be surprising that on a regular screen, there's a 1:1 matchup between the screen pixels and the pixels in the screenshot. Thus the image is the same size as the Directory icon when it was on the screen.

>Now let's take a look at a Retina screenshot:

>![Retina OS X Screenshot](https://cloudup.com/iJZmCTXTBFG+)

>With the knowledge from above, that OS X uses double the amount of pixels to draw the screen on a Retina monitor, it makes sense that the actual screenshot itself would contain twice the amount of pixels compared to the regular screenshot.

>"The Retina Screenshot Problem"

>Unfortunately, now the Web Browser displays the Retina screenshot too large! It's shown on the screen at twice the physical size compared to the part of the screen that was captured. This is what we call "The Retina Screenshot Problem."

>In a perfect world, the Web Browser might know that the image is a screenshot, that it was taken on a Retina display, and that it should scale it down by a factor of 2. But that's not the world we live in, so your application needs to do it explicitly.

There are many solutions to create a workaround, here are a two of the simplest options:
- Download a third-party app, such as https://github.com/seandougall/Halver

OR
- Go to System Preferences -> Display -> Click "More Space"
