### ISSUE TITLE
Uploading failed no extra information

### ISSUE THREAD

**Issue by AndreasBackx** [mileswd/mac2imgur#48]
Could the app provide us with some information to why uploading has failed? I can't seem to upload any screenshots atm.

**Comment by AndreasBackx** [comment]
Thank you for the quick response, could there be a release perhaps?

**Comment by mileswd** [comment]
Done!

By the way, you can find extra information about any error by checking ```Console.app```

**Comment by AndreasBackx** [comment]
Thank you very much, auto update popped up and installed successfully!
