### ISSUE TITLE
Bell on successful upload

### ISSUE THREAD

**Issue by tpwrules** [mileswd/mac2imgur#49]
Hey! For various reasons I've disabled the notification center in OSX so I can't get notifications of when an upload is successful. Other apps I've used play a sound and light up the icon instead of a notification. Could you implement something like this?

**Comment by mileswd** [comment]
This is the first I've heard of someone manually disabling notification center, unfortunately it's quite an important part of mac2imgur - even the notification sound that plays is handled by the notification center.

I don't know whether you've had a chance to try this application yet, but something very similar is already implemented (#31) - when an image is being uploaded, the icon changes from ![](https://raw.githubusercontent.com/mileswd/mac2imgur/master/mac2imgur/Images.xcassets/StatusInactive.imageset/Inactive%401x.png) to ![](https://raw.githubusercontent.com/mileswd/mac2imgur/master/mac2imgur/Images.xcassets/StatusActive.imageset/Active%401x.png)

I know that this doesn't give an indication of whether or not the upload was successful, but it does show that the upload has completed.

**Comment by tpwrules** [comment]
I use Growl so I can have more flexibility with the notifications. The arrow works though. I only ask because the app I had to ditch because they went paid played a bell instead of a notification.
