### ISSUE TITLE
Option to un-retina screenshots

### ISSUE THREAD

**Issue by k-bx** [mileswd/mac2imgur#50]
I feel uncomfortable doing screenshots when I'm on retina display, since they are "huge". I'd like an option (maybe a default one) to compress retina-screenshots to look like regular ones.

Thank you!

**Comment by mileswd** [comment]
As per #52, I'm currently working on this - when the feature is complete and tested it will be pushed out as an automatic update.

Thanks for the request :+1:

**Comment by k-bx** [comment]
Perfect! Thanks
