### ISSUE TITLE
Doesn't auto-upload after screenshot (Related to Dropbox?)

### ISSUE THREAD

**Issue by treblig** [mileswd/mac2imgur#55]
When I take a screenshot, it doesn't auto upload. However, it may be related to the fact that my screenshots get auto-uploaded to Dropbox. I changed the default location of my screenshots to ~/Dropbox/Screenshots. Will mac2imgur detect them there?

**Comment by mileswd** [comment]
Yep, mac2imgur should detect and upload screenshots saved to the folder specified in the ```com.apple.screencapture``` defaults. I don't think any other application would affect this, unless it was moving/deleting the screenshots from the folder.

It may also be worth noting that after making any changes to the screencapture defaults, you have to run ```killall SystemUIServer``` for the changes to take effect.

**Comment by treblig** [comment]
Got it! My path was stored wrong there, and Dropbox had symlinked it. Thanks!
