### ISSUE TITLE
History

### ISSUE THREAD

**Issue by danpaulson** [mileswd/mac2imgur#58]
Would be swell to be able to see the last 5 uploads or so.

**Comment by mileswd** [comment]
There's already something sort of like this, if you click the notification center icon (top right of your screen) under the notifications tab you can see all recent notifications from mac2imgur. You can click any notifications that contain an Imgur link, which will open the selected image in your browser.

However, if you think this is unsuitable, I'll happily add a menu containing recent uploads to the application.

**Comment by PunKeel** [comment]
Reminds me of something ... :)

**Comment by mileswd** [comment]
@PunKeel I know where I'd be copying the code from ;)

**Comment by danpaulson** [comment]
That seems to work, though I think in the end it may still be a decent feature to have if it's easy. I don't use notification center, so I would have never noticed that if I hadn't asked.

My personal best case scenario would be the last 5 displayed on the m2i menus under Select Images, and a option to disable history in Options for those that don't want that (perhaps selected by default if you're concerned about disrupting user patterns).

Either way, thanks, I can get by now!

**Comment by mileswd** [comment]
Added this because apparently many people don't even know notification center even exists and those that do choose not to use it:
http://www.reddit.com/r/mac/comments/37ohw5/does_anyone_even_use_notification_center/

@PunKeel Borrowed some of your code, thanks! :smile:

**Comment by danpaulson** [comment]
:+1: 

Thanks for this, appreciated!
