### ISSUE TITLE
Link to my profile

### ISSUE THREAD

**Issue by Skippern** [mileswd/mac2imgur#59]
Would be great if I could have a shortcut to my imgur profile from the menu, the same way `Scrobomatic` have to last.fm

**Comment by mileswd** [comment]
Thanks for the feature request!

I quite like this idea, but could you please clarify which profile page the application should open?

I'm not sure whether you mean:
https://username.imgur.com/all/
or
https://imgur.com/user/username

**Comment by Skippern** [comment]
I didn't know there where more than one profile

After looking at them, https://username.imgur.com/all/ has what I was thinking about

**Comment by mileswd** [comment]
Thanks for the quick response.

You will see this in an update soon :)

**Comment by mileswd** [comment]
Added in 5880a2fe4092eaaf0e5197d6b17c898bb489e76d
