### ISSUE TITLE
Resizing stopped working

### ISSUE THREAD

**Issue by k-bx** [mileswd/mac2imgur#60]
After getting an update yesterday, I just did a screenshot and it uploaded non-resized from my retina screen: https://i.imgur.com/QoKhnix.png

It worked before. "Downsize from retina" option is checked.

**Comment by mileswd** [comment]
@k-bx Nice catch, I didn't notice this because I don't have a retina display.

Could you possibly test this this development build to ensure that I've fixed the issue?
https://www.dropbox.com/s/zd2dqzee6klh4zm/mac2imgur.zip?dl=1

Thanks in advance :+1:

**Comment by k-bx** [comment]
@mileswd let's see: https://i.imgur.com/RiACMg5.png

Yeah, seems fixed. Thanks!

**Comment by mileswd** [comment]
Pushed out as an automatic update.

Thanks for spotting this bug, @k-bx :smile:

**Comment by k-bx** [comment]
Sweet, thanks!
