### ISSUE TITLE
Support for [CMD ⌘] - [CTRL] - [SHIFT ⇧] - [4] ?

### ISSUE THREAD

**Issue by FezVrasta** [mileswd/mac2imgur#61]
I'd like to get support for the <kbd>cmd ⌘</kbd> <kbd>ctrl</kbd> <kbd>⇧</kbd> <kbd>4</kbd> shortcut.

It's the shortcut to directly copy the selected part of screen to the clipboard.
In this way I would not have to save them somewhere just to upload them and get them automatically deleted.

I would use the <kbd>cmd ⌘</kbd> <kbd>⇧</kbd> <kbd>4</kbd> when I want just to save the screenshot locally, and the other one when I want to upload it on Imgur.

Thanks!

**Comment by mileswd** [comment]
This feature was requested a while back (#27), but unfortunately I couldn't implement it as there is no proper API for detecting changes to the system pasteboard - this means the application would have to poll the system pasteboard many, many times every minute. As you can imagine, this is very inefficient and has a negative effect on battery life. Even if we chose to do this, as far as I know, there is no way to differentiate between images and screenshots - meaning whenever the user copied an image to their clipboard, it would be uploaded.

I am deeply sorry about the state of screenshots in OS X, but unfortunately this issue is out of my hands - it's something only Apple can implement.

If Apple ever do introduce a proper screenshot API or similar, I won't hesitate to add this feature.

Thanks for the feedback

**Comment by Tyilo** [comment]
As I have suggested before you could call out to `/usr/sbin/screencapture` directly when the shortcut is triggered.

**Comment by FezVrasta** [comment]
Yup

**Comment by mileswd** [comment]
@Tyilo I appreciate your suggestion, but that would require either:
- The user manually changing the current global keyboard shortcut for taking screenshots, then manually allowing mac2imgur as an assistive/accessibility device through the security pref pane.
- Manually allowing mac2imgur as an assistive/accessibility device, then binding to a different shortcut, which is non default to OS X

I try to develop my applications following the KISS principle - I don't want to force people to jump through extra hoops just to use the application, nor make the application obtrusive.

**Comment by Tyilo** [comment]
@mileswd You don't need to have mac2imgur as an assistive/accessibility device to make a global keyboard shortcut.

For instance you could use https://github.com/shpakovski/MASShortcut or the Carbon API directly.

**Comment by mileswd** [comment]
@Tyilo Thanks, I wasn't aware of that method. However, I'm not sure how long the Carbon API has left as a part of OS X, considering that most of it was deprecated back in 10.8.

**Comment by FezVrasta** [comment]
You may just say that you don't want to work on this feature and just ask someone to PR it.

**Comment by Tyilo** [comment]
@mileswd As far as I know it is the only way of registering a global shortcut, so I don't think it'll go away for a couple of years if ever.

**Comment by mileswd** [comment]
@FezVrasta If there was a clean way of doing this I would add it myself - but unfortunately there isn't.

@Tyilo The reason I initially mentioned accessibility access is because AppKit has 
```swift
NSEvent.addGlobalMonitorForEventsMatchingMask(mask: NSEventMask, handler: (NSEvent!) -> Void)
```

**Comment by Tyilo** [comment]
https://github.com/Kentzo/ShortcutRecorder also uses the Carbon API and is also very popular like MASShortcut.

**Comment by Tyilo** [comment]
https://github.com/davedelong/DDHotKey also uses that API, so I think it's safe to use the Carbon API in mac2imgur or use one of the frameworks.

**Comment by mileswd** [comment]
@Tyilo Fair enough. Although I'm still not convinced that the Carbon API should be used nowadays, I'll take @FezVrasta's advice. I'd accept a PR with a pure Swift implementation of this feature.

**Comment by Tyilo** [comment]
@mileswd I don't think a pure swift version is possible, see http://stackoverflow.com/a/29801216/640584

**Comment by mileswd** [comment]
@Tyilo Ah, okay. For now, I think the best thing is to hang on until WWDC (in just over a week) as Apple will be announcing their updates to both OS X and Swift, which might affect this issue.

**Comment by FezVrasta** [comment]
@mileswd could you at least allow us to upload images stored in the clipboard like it happens on the Imgur website?

**Comment by Tyilo** [comment]
@mileswd Any new info from WWDC?

**Comment by mileswd** [comment]
@Tyilo No improved screenshot API, but more Carbon API deprecations - but luckily the shortcut API wasn't one of them!

I'll have some news soon...

**Comment by Tyilo** [comment]
Any news?

**Comment by mileswd** [comment]
@Tyilo Sorry for not updating you sooner, I've been pretty busy and haven't had time to finish off the work I started - it includes the following:
- Rename app (to avoid any legal issues)
- Switch from monitoring for screenshots to using `screencapture` directly
- Customisable shortcuts
- Full UI redesign (includes new screenshot browser and preferences)

**Comment by Tyilo** [comment]
Sounds cool ;)

**Comment by mileswd** [comment]
Agreed, Carbon API or one of those frameworks would be fine 👍

However, after reviewing this issue, I do not currently have any plans on implementing this, unfortunately. I'd prefer to leave the actual capturing of screenshots to the system itself, as the primary purpose of mac2imgur has always been just to upload screenshots and other images.

Apologies.

**Comment by FezVrasta** [comment]
Then you could at least allow us to upload pictures from the clipboard..

**Comment by mileswd** [comment]
Sure thing! I'll look into it :+1:
