### ISSUE TITLE
Option to confirm uploading

### ISSUE THREAD

**Issue by kiliankoe** [mileswd/mac2imgur#62]
Love mac2imgur so far, but it seems a recent update has removed the option to confirm uploads with an alert. Is this change intentional? I'd rather not upload every single screenshot I take. 

Otherwise: :+1:

**Comment by kiliankoe** [comment]
Awesome, thank you!

![](http://i.giphy.com/HJ8NsNtn9VswE.gif)

**Comment by mileswd** [comment]
`mac2imgur` -> `Preferences` -> `Check for Updates...` :smile:
