### ISSUE TITLE
Mac2Imgur sent several "screenshot uploaded" notifications after my Mac restarted for updates

### ISSUE THREAD

**Issue by NathanCJohnson** [mileswd/mac2imgur#63]
After my Mac installed updates and restarted, Mac2Imgur sent around 10-15 screenshot notifications at once, I'm not sure if it actually uploaded anything though. I'm on OS X 10.9.5 on a MacBook Air and have Mac2Imgur v3.0 (174).

**Comment by mileswd** [comment]
Thanks for reporting this - I wasn't sure if anyone else was actually experiencing this.

I actually implemented a safeguard against this issue in 2790c80ff75ab0f674e55efa8ad7fbb8b6cd8328. I'm not quite sure why after some restarts NSMetadataQuery does this, as far as I know it seems to be a bug in OS X.

I have just pushed out an update, including this fix. Just click `Preferences` -> `Check for Updates...` and you should be good to go!

**Comment by NathanCJohnson** [comment]
Awesome! Thanks for the quick response.

**Comment by iCHAIT** [comment]
Happened a couple of times for me too, I took two screenshots but they did not upload instantly, when I restarted my mac I received the screenshot notification for those. I'll try out the latest version :+1:
