### ISSUE TITLE
Albums support

### ISSUE THREAD

**Issue by tommiv** [mileswd/mac2imgur#65]
Any chance for albums support? Looks like it's [possible](http://api.imgur.com/endpoints/image#image-upload).

**Comment by mileswd** [comment]
Sounds like a good idea, I'll look into it! :+1:

**Comment by lindskogen** [comment]
What would be the use case? I guess it would make sense when you drop multiple images on the menu bar icon... Maybe something like - when you quickly grab multiple screenshots in succession?

**Comment by tommiv** [comment]
One possible use case is to store your screenshots in private album, while your imgur profile is public (it's possible to capture sensitive information accidentally); the second one is just organisation matter – put fun pics in fun pics album, put your tomorrow presentation slides in album "tomorrow-presentation-slides" and store screenshots where it belongs – in album "screenshots".

**Comment by growlsworth** [comment]
I think a major use case is to keep all screenshots in a "screenshots" album so it's easy to mass delete old screenshots.

**Comment by joelworsham** [comment]
I absolutely would love to see this. I don't like that my imgur account is cluttered with screenshots. I also don't like that they're public by default.

**Comment by mileswd** [comment]
Done - will be available as an automatic update soon… :smile:
