### ISSUE TITLE
Press enter on upload confirmation to confirm

### ISSUE THREAD

**Issue by eriknomitch** [mileswd/mac2imgur#66]
I'd love if "Upload" was selected as the default here and I could just press enter to confirm.  Additionally, (much like the Photoshop save dialog) pressing "c" to cancel would be great.

It's possible that I'd be able to implement.  Thoughts?

Great app by the way.

Erik

**Comment by mileswd** [comment]
Thanks for the feedback! :+1:

The "Upload" button not being selected was actually a bug, so apologies about that. I have also added the "c" shortcut to cancel, as you suggested.

An update including this should be pushed out soonish!

**Comment by eriknomitch** [comment]
Excellent!  Thank you for the super quick turnaround.
