### ISSUE TITLE
it gives me rainbow wheel all day

### ISSUE THREAD

**Issue by blimmer** [mileswd/mac2imgur#73]
Anytime I click the mac2imgur menu bar icon, it gives the the beach ball. Happy to help diagnose.

**Comment by mileswd** [comment]
May I ask what version and build of both OS X and mac2imgur you are running?

Thanks in advance

**Comment by blimmer** [comment]
Of course. OS X 10.10.5, mac2imgur version 3.0 (183).

**Comment by mileswd** [comment]
You're up to date - awesome. :+1: 

Can you take a look in `Console.app` and see if the application is spitting out any error messages?

**Comment by blimmer** [comment]
Unfortunately, I'm not seeing anything. I'll keep an eye on it with a filter.

**Comment by mileswd** [comment]
A few things to try first:
- Try deleting the stored preferences by running `defaults delete com.mileswd.mac2imgur`
- Make sure mac2imgur isn't in your login items

If neither of those changes anything, try to do this:

1. Open mac2imgur, and click the menu bar item (causing it to beachball/hang)
2. Run `sudo kill -SEGV $(ps -A | grep -m1 mac2imgur | awk '{print $1}')` in `Terminal.app` (this will force the application to crash and save a crash report
3. Open mac2imgur (but don't do anything this time) - the crash report will then be automatically sent to me (and should hopefully help me figure out what's going on)

Thanks once again :smile:

**Comment by blimmer** [comment]
Interestingly, it seems like this might be related to login items. When I visited the System Preferences login items pane, everything froze up. There were several apps I've deleted in there marked as "Unknown". After removing those, things seem to be moving along much quicker. I'm not getting the beach ball anymore. Seems like this is an OS level problem with login items vs. a problem with your app!

**Comment by mileswd** [comment]
That could be it! Thanks for the report anyway - maybe I need to go over the login items implementation some time, just to be sure. :+1:
