### ISSUE TITLE
Support for dropping images (not files)

### ISSUE THREAD

**Issue by MaartenStaa** [mileswd/mac2imgur#74]
It would be nice if I could drag images from e.g. the Photos app, or from Chrome, and drop them on the status bar icon, rather than having to save it to disk first, and then dragging the file to it.

**Comment by lfaoro** [comment]
:+1:

**Comment by danpaulson** [comment]
👍

**Comment by mileswd** [comment]
This feature has been implemented for provided pasteboard images (`NSTIFFPboardType`) meaning dragging and dropping images from most applications will work, however receiving promised files (`NSFilesPromisePboardType`) has not been implemented - consequently drag operations from a few applications such as `Photos.app` is not possible. At the moment, I'm not sure if (or when) I'll add support for promised files.

This feature will be available in an automatic update soon 👍
