### ISSUE TITLE
[idea] Clear clipboard right after screenshot is taken

### ISSUE THREAD

**Issue by azamatms** [mileswd/mac2imgur#77]
Essentially once you drag the selection and let go, the app would clear your clipboard so when you go to paste the link somewhere you won't accidentally send someone whatever was previously on your clipboard.

Let me know if this makes sense, would be a nice additional feature that could be toggled in Preferences.

**Comment by Tyilo** [comment]
:+1:

**Comment by lfaoro** [comment]
Flow:
- Screenshot
- Upload to imgur
- Copy imgur link to Pasteboard
- Link available in Pasteboard
- Once the link is pasted the Pasteboard gets cleared

I don't know how you could achieve this programmatically...
You can't get notified when the user uses the pasteboard

I guess the only way is having an NSTimer checking the pasteboard for content after 1 minute.
If the content of the Pasteboard == imgur link, then clear the Pasteboard

**Comment by Tyilo** [comment]
No the flow would be:

   - Screenshot
   - Clear the Pasteboard
   - Upload to imgur
   - Copy imgur link to Pasteboard
   - Link available in Pasteboard


On Thursday, September 10, 2015, Leonard <notifications@github.com> wrote:

> Flow:
>
>    - Screenshot
>    - Upload to imgur
>    - Copy imgur link to Pasteboard
>    - Link available in Pasteboard
>    - Once the link is pasted the Pasteboard gets cleared
>
> I don't know how you could achieve this programmatically...
> You can't get notified when the user uses the pasteboard
>
> I guess the only way is having an NSTimer checking the pasteboard for
> content after 1 minute.
> If the content of the Pasteboard == imgur link, then clear the Pasteboard
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mileswd/mac2imgur/issues/77#issuecomment-139072707>.
>


-- 
Asger Hautop Drewsen

**Comment by iCHAIT** [comment]
:+1:

**Comment by azamatms** [comment]
Thanks @Tyilo 

He described it pretty well, could help avoid some embarrassing situations in IRC or Instant Messaging.

**Comment by mileswd** [comment]
This makes a lot of sense - great idea!

Added in 39dfb192bd9d3a5ad470d1caf090af21f7e08b21, expect an update to be pushed soonish :smile:

**Comment by iCHAIT** [comment]
@mileswd 
Has this been pushed in any of the updates?
Just suffered sort of an embarrassing situation on a chat  :(

**Comment by mileswd** [comment]
@iCHAIT Yep! You can turn it on from the preferences menu :smile: 
![](https://i.imgur.com/Sd9kNGt.png)

**Comment by iCHAIT** [comment]
Damn, should have done this earlier itself.

Thanks :)
