### ISSUE TITLE
Uploading slow? 

### ISSUE THREAD

**Issue by vicngtor** [mileswd/mac2imgur#79]
First of all, thank you for making this plugin. I have been using Dropbox's screenshot tool for a while now and it sucks because the url generated is some dropbox page which doesn't share well on messenger as they are not type:jpeg/png

I do notice your tool takes significantly longer from taking a screenshot to finished uploading and having the link in my clipboard. Is this something that can be optimized?

**Comment by mileswd** [comment]
Sorry for not getting back to you sooner on this one.

I haven't used Dropbox in a while, but if I recall correctly, Dropbox cheats a little to make this feel faster: I believe a URL is generated as soon as the screenshot is taken - even if the file itself hasn't finished uploading to Dropbox yet.

Unfortunately something like this could not be implemented as the Imgur API requires the file to be uploaded first, for a link to be generated.

However, I'm in the process of rewriting the screenshot monitoring part of mac2imgur - the new method detects screenshots more instantaneously and can reduce waiting time by a few seconds in a best case scenario. You can track this in #80.

**Comment by mileswd** [comment]
#80 has been pushed as an automatic update.
