### ISSUE TITLE
Doesn't upload screenshots automatically

### ISSUE THREAD

**Issue by diversario** [mileswd/mac2imgur#80]
As discussed here https://twitter.com/diversario/status/666315414142590976 mac2imgur doesn't do anything upon taking a screenshot.

Console.app has no messages from the app except

```
11/17/15 13:22:30.551 mac2imgur[63256]: [Crashlytics] Version 3.3.4 (82)
```

I tried it with `com.apple.screencapture` not even existing; also tried setting location explicitly to an existing folder – images were saved there but still no action from mac2imgur.

I'm running OS X 10.11.1, mac2imgur 3.0. Don't really know what else to try!

**Comment by mileswd** [comment]
Sorry I didn't get back to you sooner!

I've written a test application which will print a fair amount of debugging stuff, which should hopefully help solve the problem.

Open it, try taking a screenshot and post what comes up! :smile:

http://expirebox.com/download/d1940478d498a829d8f22a46e5dc6e8e.html

**Comment by diversario** [comment]
I did but nothing showed up in the window!

**Comment by mileswd** [comment]
Was anything displayed, whatsoever?

**Comment by diversario** [comment]
Just the name of the app.

**Comment by b005t3r** [comment]
Same problem here. I'm still on Yosemite (10.10.5), so I can't even start your debugging app (it requires the next OS X).

**Comment by mileswd** [comment]
@b005t3r Thanks for the info! If possible, try some of the debugging steps from the Twitter exchange that @diversario posted above.

I'll look into this properly ASAP! :smile:

**Comment by kblanks** [comment]
I have this same issue and screenshot uploading does not work until I quit and re-open the app. Version 3.0 (185)

**Comment by msafi** [comment]
Upload doesn't start automatically for me either. I'm on El Capitan. Dragging & dropping the image on the menu bar icon causes the image to upload, but even though "Delete on upload" is checked, it doesn't delete after upload completes.

**Comment by mileswd** [comment]
I've just finished writing an initial implementation of a FSEvents based screenshot monitor (as opposed to the previous method using NSMetadataQuery). Hopefully this will resolve this issue and also provide a slight speed boost!

It'd be great if you could test this development build, which is a compiled version of 449b370d0cfb477693a971be49d436bc96bfb038:

http://expirebox.com/download/d4f79eb622f32ed4a761774bc7aa76c0.html

Thanks!

**Comment by msafi** [comment]
Hey! This works and it's fast!!

**Comment by diversario** [comment]
Hell yeah, it works! :+1: :100: :cake: :tada: :shipit:

**Comment by kblanks** [comment]
Working great! :+1:

**Comment by PunKeel** [comment]
This means we won't be able to change the storage path ... isn't it ? ;)

**Comment by diversario** [comment]
Mine's actually changed and it still works.

**Comment by PunKeel** [comment]
But if you change it while mac2imgur is running, it won't consider the change (I assume)

**Comment by diversario** [comment]
Oh. Well, not sure about that but restarting it is as easy as it could be.

**Comment by mileswd** [comment]
@PunKeel Yep, restarting mac2imgur would be required. Hopefully this isn't too much of an issue?

**Comment by PunKeel** [comment]
Not an issue, but should be written somewhere so that it doesn't become a recurring question ;)

**Comment by mileswd** [comment]
@PunKeel Good call :+1:

Just pushed this out as an update - thanks for testing! :smile:
