### ISSUE TITLE
Dragging a picture from a stack folder to the status bar icon doesn't work

### ISSUE THREAD

**Issue by Allavaz** [mileswd/mac2imgur#83]
It shows the plus icon when I'm about to drop it on the status bar icon but still doesn't upload the picture.

**Comment by mileswd** [comment]
Unfortunately this is not a bug in mac2imgur, but appears to be a longstanding bug in macOS itself - http://openradar.appspot.com/radar?id=1745403

I understand that this is a minor annoyance, but you can always work around this bug by using the "Upload Images…" option or dragging the file(s) from Finder.
