### ISSUE TITLE
Upload fails if location of screenshot folder changes? 

### ISSUE THREAD

**Issue by vicngtor** [mileswd/mac2imgur#85]
I just realized that changing the location of the screenshot location via `defaults write com.apple.screencapture location ~/my-new-screenshot-location` causes mac2imgur to fail. 

Can someone confirm this?

**Comment by PunKeel** [comment]
I confirm :( https://github.com/mileswd/mac2imgur/issues/80#issuecomment-161501895

**Comment by vicngtor** [comment]
With reference to the line, 
```
    var screenshotDirectoryURL: NSURL? {
        // Check for custom screenshot location chosen by user
        if let path = defaults.persistentDomainForName("com.apple.screencapture")?["location"] as? NSString {
            let standardizedPath = path.stringByStandardizingPath
            
            // Check that the chosen directory exists, otherwise screencapture will not use it
            var isDir = ObjCBool(false)
            if fileManager.fileExistsAtPath(standardizedPath, isDirectory: &isDir) && isDir {
                return NSURL(fileURLWithPath: standardizedPath)
            }
        }
        
        // If a custom location is not defined (or invalid) return the default screenshot location (~/Desktop)
        return fileManager.URLsForDirectory(.DesktopDirectory, inDomains: .UserDomainMask).first
    }

```

This is my terminal output: 
```
$ defaults read com.apple.screencapture location
/Users/vng/Screenshots

$ ls -lah 
drwxr-xr-x   12 vng   staff   408B Feb 12 13:50 Screenshots
```

I don't quite understand why this is not working. Any ideas?

**Comment by PunKeel** [comment]
The `defaults` is read on startup, if you change it mac2imgur will still be watching the former location

**Comment by mileswd** [comment]
> The `defaults` is read on startup, if you change it mac2imgur will still be watching the former location

This is correct. To change the screenshot location, unfortunately the application must be restarted.

I'll add a note in the README to make this behaviour clearer 👍
