### ISSUE TITLE
StatusBar Icon Freeze when touch her

### ISSUE THREAD

**Issue by ownmas** [mileswd/mac2imgur#87]
OS X 10.11.3

After that mac is think about 10 sec and icon unfreeze
![img_1357](https://cloud.githubusercontent.com/assets/10982852/13652191/da460998-e65b-11e5-83a0-5c9280441841.JPG)

**Comment by ownmas** [comment]
I understand, that mac2imgur conflict with Google Drive, he freeze like that. But how to fix it i don't know,

**Comment by mileswd** [comment]
Resolved in the latest update :+1:
