### ISSUE TITLE
Add button in notification with name "Copy link"

### ISSUE THREAD

**Issue by ownmas** [mileswd/mac2imgur#88]
Sometimes i don't need to copy screenshot URL right now, please, create in settings switch, which add "Copy link" button to notification :+1: 

And create in settings the notify retention time value.

**Comment by mileswd** [comment]
Both of your suggestions have been implemented and will be available in an automatic update soon. 👍

However, instead of adding a button to the notification, a submenu has been added to the `Recent Uploads…` menu, as below:

![](https://i.imgur.com/o60pCC9.png)
