### ISSUE TITLE
Doesn't delete after upload or even allow it manually

### ISSUE THREAD

**Issue by sama7** [mileswd/mac2imgur#89]
Title summarizes the issue. I have "Delete After Upload" checked in my preferences but the files don't actually delete. Even trying to manually delete them fails (see [here](https://i.imgur.com/qBSDWGV.jpg)). Anyone else having this problem, and any suggestions?

I'm running El Capitan 10.11.3.

**Comment by olessavluk** [comment]
It looks like an OS X bug. Try to reboot your system or you can just relaunch Finder.app.

**Comment by sama7** [comment]
Thanks @olessavluk, relaunching Finder works.
