### ISSUE TITLE
Is there any apple script or shell script support?

### ISSUE THREAD

**Issue by Modi34** [mileswd/mac2imgur#91]
I want to use hazzel to upload new gifs created with another app to imgur using mac2imgur app

but Im not sure how to do it//

**Comment by Modi34** [comment]
I tried 
tell application "/Applications/main/mac2imgur.app" to open "/Users/modi34/Desktop/1.gif"
but It returned an alert with error

**Comment by mileswd** [comment]
Done 👍

You can now open files with mac2imgur - this feature will be available in an automatic soon.
