### ISSUE TITLE
App crashes almost instantly

### ISSUE THREAD

**Issue by VeryInsane** [mileswd/mac2imgur#93]
My exact steps:

- Downloaded the latest version from main GitHub page
- Moved to Applications
- Opened it 
- I was prompted to install the newest version, I did
- It opened again and I setup my Imgur account
- I took 2 screenshots, the app was working, I clicked the notification toast and opened my uploaded images
- The app crashes
- I open the app again, it crashes

I can't get it to stay open for more than 30 seconds

![screen shot 2016-08-02 at 6 10 32 pm](https://cloud.githubusercontent.com/assets/5018400/17347191/744e6268-58dc-11e6-9f71-dd1e0d677646.png)

**Comment by mileswd** [comment]
Thanks for the report!

So far, I've found and fixed one of the crash bugs (when you hover over Recent Uploads).

Could you possibly paste the contents of the crash reports from `Console.app`?

Thanks in advance :+1:

**Comment by kenzierocks** [comment]
On Yosemite 10.10.5, just updated, crashes immediately. This is in `Console.app`'s messages:
<img width="1195" alt="screen shot 2016-08-02 at 4 15 11 pm" src="https://cloud.githubusercontent.com/assets/2093023/17348634/6d924436-58cc-11e6-8fad-c812b992b171.png">

**Comment by VeryInsane** [comment]
Here you go:

![screen shot 2016-08-02 at 7 22 09 pm](https://cloud.githubusercontent.com/assets/5018400/17348756/9775a238-58e6-11e6-8ff1-3f15bfe6401e.png)

https://pastebin.com/QKkDiWJa

**Comment by mileswd** [comment]
Thanks for the crash reports 👍

I'm going to pull the update for now and investigate further tomorrow - unfortunately I haven't been able to replicate this issue on either macOS 10.12 or macOS 10.11 so far.

**Comment by VeryInsane** [comment]
I managed to update to 4.0 (205) and I haven't noticed a crash yet.

**Comment by mileswd** [comment]
Released another update patching a bug when opening the "Upload to Album" menu, which occurs when there is an album that has no title.

Didn't spot this one sooner as our underlying Imgur library (`ImgurSession`) is not audited for nullability.

Thanks for your assistance!
