### ISSUE TITLE
Copy image URL, not imgur URL

### ISSUE THREAD

**Issue by andreiglingeanu** [mileswd/mac2imgur#96]
Is there a way to not copy the link to imgur, but rather the direct URL to the image itself?

**Comment by mileswd** [comment]
Sorry, I'm not sure I understand what you mean.

By default, the direct link to the image (`i.imgur.com`) is copied to the clipboard.

**Comment by andreiglingeanu** [comment]
Ah, I didn't tested it very carefully, it works fine. Sorry for bugging!
